# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/dexter/sandbox/CplusplusWorkspace/DEMO_CMAKE/pgm/HelloWorld/CMakeLists.txt))

/Users/dexter/sandbox/CplusplusWorkspace/DEMO_CMAKE/macbuild/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/local/bin/cmake -H/Users/dexter/sandbox/CplusplusWorkspace/DEMO_CMAKE/pgm -B/Users/dexter/sandbox/CplusplusWorkspace/DEMO_CMAKE/macbuild
